#+STARTUP: showall
#+TITLE:     La teoría de la elección social
#+AUTHOR:    Examen parcial
#+DATE:      8-3-2026
#+OPTIONS:   H:2 num:t toc:f \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:https://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LANGUAGE:  es



*Trabajos parcial y final*

*Elección Pública III*

*Primavera 2026*

* Fechas importantes

- Anuncio y justificación del tema: 16 de marzo
- Entrega del trabajo parcial: 6 de abril
- Entrega y presentación del trabajo final: el día y hora que dirección escolar nos asigne para el examen final

* Enunciado

Usará el /agenda setter model/ para analizar algún proceso de negociación real que sea de su interés. Le hará cambios leves a las premisas del modelo para que se adapte mejor a la problemática elegida.

* El caso de estudio

El primer paso consistirá en *seleccionar su caso de estudio*. Algunos ejemplos de posibles procesos de negociación son los siguientes:

1) Marzo 2026: La reforma electoral de CSP
2) Febrero 2026: SCOTUS v POTUS sobre aranceles
3) Desde 2024: coalición minoritaria de Macron v AN francesa
4) Desde 2024: Milei v oposición en el Congreso argentino
5) La ``compra'' de Groenlandia
6) Las instituciones de la Unión Europea
7) 1939--40: la Guerra de Invierno entre la URSS y Finlandia
8) Coalición de Netanyahu v la Knesset en Israel
9) Marzo 2026: Anthropic v Pentágono

No tiene que circunscribirse a estos temas, indague un proceso que le parezca interesante para modelarlo y sacar conclusiones. 

Anunciará el caso de su elección el 16 de marzo en una página. Su anuncio de incluir una justificación de la decisión que tomó  así como una primera formulación de la pregunta que guiará su investigación. Dos o tres párrafos claros y bien redactados son suficientes.

* El trabajo parcial

El siguiente paso consistirá en *investigar fuentes* diversas (prensa, libros de historia, leyes, papers académicos, etc.) para entender el caso de su elección con detalle. Sumérjase para ir construyendo la narrativa de fondo: quienes son los actores; cuáles de entre ellos son más relevantes y por qué; qué objetivos parecen perseguir; qué restricciones estructurales enfrentan; cuáles son las reglas formales o informales de relevancia para la interacción; quién ha escrito al respecto; qué se entiende mejor y qué sigue en suspenso; y mucho más.

Entregará su trabajo parcial el 6 de abril. Consistirá en un reporte breve y claro donde precise sus preguntas y desarrolle la historia de fondo. Detallará lo que ha investigado y sea relevante para su análisis, sugieriendo el modo como el /agenda setter model/ podría aplicarse al análisis de la negociación. 

* El trabajo final

Estas instrucciones las detallaré después de la entrega del trabajo parcial. Además de la entrega del trabajo final, hará una breve presentación ante la clase. 

* Nota sobre la inteligencia artificial

Si usa algún LLM de inteligencia articifial deberá hacerlo explícito en sus entregas. Además, deberá incluir un apéndice que elabore qué herramienta(s) usó y cómo, detallando los /prompts/ que ocupó, cómo los fue refinando, y especialmente, cómo corroboró la veracidad de lo que arrojó su búsqueda.

¡Mucha suerte!

# https://animalpolitico.com/politica/partido-del-trabajo-supervivencia-poder-veto-morena
# 7) 2021--26: Guerra de Ucrania


