Glen Weyl de Microsoft Research ha estado promoviendo el voto cuadrático como método alternativo a los termómetros en las encuestas (/feeling thermometers/). Los termómetros quizás incentiven al entrevistado a imponer el máximo de puntos a cada asunto con el que concuerda parcialmente---quizás para cancelar los votos contrarios de otros. 

Esto cambia si los votos fueran finitos, como en el método de votación cuadrática. Cada entrevistado cuenta con un presupuesto de créditos de voz, que puede usar para mostrar acuerdo o desacuerdo con cada asunto. Está permitido dar más de un voto a favor o en contra de un asunto, pero cada voto adicional cuesta más que el anterior. El primer voto por cuelquier asunto cuesta 1 crédito. Dos votos por el mismo tema, en cambio, cuestan 4 créditos (2 al cuadrado), tres votos cuestan 9 créditos (3 al cuadrado). Podrías asignarle el máximo de 5 votos a favor o en contra a un asunto, pero consume íntegramente el presupuesto de 25 créditos. 
* issues
- Todos los gobiernos deben imponer un impuesto al carbono para limitar el calentamiento global a 2°C
- México debe legalizar las drogas duras como la heroína y la cocaína
- Los gobiernos deben imponer mandatos de vacunación contra la covid-19
- Debe cancelarse la construcción de la refinería de Dos Bocas y reasignar el presupuesto
- Los gobiernos deben pagar indemnizaciones por el colonialismo
- México debe permitir la reelección consecutiva del presidente de la república
- La CFE representa el interés de los mexicanos y debe ser un actor preponderante
- Las empresas no deberían poder cabildear en el Congreso
- El gobierno debe prohíbir la venta de bebidas azucaradas a menores de edad
- Debe legalizarse la muerte asistida

- México debe sellar su frontera sur para impedir la llegada de migrantes centroamericanos
- AMLO debe renunciar prematuramente como presidente de México
- El ejército debe regresar inmediatamente a sus cuarteles
- Aborto

- El gobierno mexicano debe cancelar el tren maya y reasignar el presupuesto a proyectos de mayor utilidad social 
* careos 10
- Alejandro Moreno
- Claudia Sheinbaum
- Enrique de la Madrid
- Enrique Alfaro
- Francisco Domínguez
- Lorenzo Córdova
- Marcelo Ebrard
- Mauricio Vila
- Ricardo Monreal
- Tatiana Clouthier
# 11. Luis Donaldo Colosio

* termómetros
totalmente en contra -10 -9 -8 -7 -6 -5 -4 -3 -2 -1  0  1  2  3  4  5  6  7  8  9  10  totalmente a favor

* voto cuadrático
votos en contra -10 -9 -8 -7 -6 -5 -4 -3 -2 -1  0  1  2  3  4  5  6  7  8  9  10  votos a favor
votos en contra -5 -4 -3 -2 -1  0  1  2  3  4  5  votos a favor
puntos restantes
 


Se consulta al grupo para decidir 10 cuestions públicas. Describa su preferencia con feeling thermometers, donde cero indica indiferencia, positivos el grado de acuerdo con el enunciado, y negativos el de desacuerdo. Al final, se sumarán los votos de todos para decidir: si la suma fuera positiva, se legislará en pro de la cuestión; en contra si fuera negativa


legalizar coca
México debe legalizar las drogas duras como la heroína y la cocaína

impesto co2
Los gobiernos deben imponer un impuesto al carbono para limitar el calentamiento global a 2°C

2 bocas
Debe cancelarse la obra de la refinería de Dos Bocas y reasignar el presupuesto

colonialismo
Los gobiernos deben pagar indemnizaciones por el colonialismo

sí reelección
México debe permitir la reelección consecutiva del presidente de la república

pro cfe 
La CFE representa el interés de los mexicanos y debe ser un actor preponderante

no lobbying
Las empresas no deben poder cabildear en el Congreso

eutanacia
Debe legalizarse la muerte asistida

no refrescos
El gobierno debe prohíbir la venta de bebidas azucaradas a menores de edad

vacunación universal
Los gobiernos deben imponer mandatos de vacunación contra la covid-19




