From http://homepage.tinet.ie/~doylep/Winset/ws_index.htm

* Winset Calculator
Winset is a computer program designed to be used in conjunction with the “portfolio allocation” model of government formation and maintenance outlined by Laver and Shepsle.

* Features
- Given a lattice of credible points defined by party ideals in any number of dimensions, the program does any or all of the following:
- Identifies the credible points in the winset of any specified credible point.
- Investigates all credible points on a given party lattice.
- Investigates the winsets of all ideal points.
- Identifies the dimension-by-dimension median point (m*) and investigates its winset.
- Identifies the strong actor and investigates the winset of its ideal point (s*).
- Identifies any holdout points (h*).
- Using a graphical illustration of the lattice, allows the user to directly manipulate party positions.
- Illustrates the position of m*, m**, s*, s** and h* on the lattice.
- Identifies m*, m**, s*, s** and h* continously as party positions are dragged to different values by the user.
- Illustrates the positions of the winpoints of a specific, user-defined lattice point on a continuous basis as party positions are dragged to different values by the user.
- Performs batch analyses of files with data on large numbers of cases, reporting the existence and identity of m*, m**, s*, s** and h*.
- Performs Monte Carlo experiments according to user-defined simulation equations for party weights, positions or position importances.
- Winset can optionally carry out the above investigations for the contender sets of the appropriate points rather than their winsets.

* The Software
Winset 5.12 works on Windows 95 and Windows NT v4.0. The Winset manual is included in RTF format.
The kit is 1,624,020 bytes in size.

Click [[http://homepage.tinet.ie/~doylep/Winset/setup.exe][here]] to download Winset v5.12
Last update by Paul Doyle, 25th June 1998
